name: Push gem
on:
  push:
    branches: [master]
    paths:
    - 'lib/*/version.rb'
jobs:
  publish_gem:
    name: Push gem to RubyGems.org
    runs-on: ubuntu-latest
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
      contents: write # IMPORTANT: this permission is required for `rake release` to push the release tag
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: ruby/setup-ruby@354a1ad156761f5ee2b7b13fa8e09943a5e8d252 # v1.229.0
    - uses: rubygems/release-gem@a25424ba2ba8b387abc8ef40807c2c85b96cbe32 # v1.1.1
    - name: Create GitHub release
      run: |
        tag_name="$(git describe --tags --abbrev=0)"
        release_title="Release version ${tag_name}"
        gh release create "${tag_name}" --verify-tag --generate-notes --title "${release_title}"
        env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
