name: Specs
on:
- pull_request
jobs:
  specs:
    name: specs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu ]
        ruby: [ "3.0", "3.1", "3.2", "3.3" ]
    steps:
    - name: Check out code.
      uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Run tests
      run: |
        bundle check || bundle install
        bundle exec rspec
